// Dicionário de Português Brasileiro — ~5000+ palavras comuns (4+ letras)
// Usado para: (1) sortear palavras secretas, (2) validar entradas dos jogadores

const DICIONARIO = new Set([
  // A
  "ABACATE","ABACAXI","ABADE","ABAJUR","ABALAR","ABALO","ABANAR","ABARCAR","ABARROTAR","ABATER",
  "ABERTO","ABICAR","ABISMO","ABÓBORA","ABOLIR","ABORDAR","ABORTAR","ABORTO","ABRAÇAR","ABRAÇO",
  "ABRIGAR","ABRIGO","ABRIL","ABRIR","ABSURDO","ABUTRE","ABUSO","ACABAR","ACAMPAR","ACASO",
  "ACEITAR","ACENDER","ACENO","ACERTO","ACESSO","ACIDENTE","ÁCIDO","ACIMA","ACORDAR","ACORDO",
  "ACOSSAR","AÇÚCAR","ACUSAR","ADAPTAR","ADESIVO","ADEUS","ADIANTAR","ADMITIR","ADORAR","ADORNO",
  "ADOTAR","ADULTO","ADVOGADO","AFASTAR","AFETO","AFOGAR","AGARRAR","AGASALHO","AGENTE","AGITAR",
  "AGOSTO","AGRADECER","AGRADO","AGRAVE","AGREDIR","ÁGUA","AGUARDAR","AGUÇAR","AJOELHAR","AJUDA",
  "AJUDAR","ALARME","ALCANÇAR","ÁLCOOL","ALDEIA","ALEGRAR","ALEGRIA","ALÉM","ALERTA","ALFACE",
  "ALGUÉM","ALGUM","ALHO","ALIADO","ALIMENTAR","ALIMENTO","ALINHAR","ALISAR","ALMOÇAR","ALMOÇO",
  "ALMOFADA","ALUGUEL","ALUNO","AMAR","AMARGO","AMÁVEL","AMBIENTE","AMIGO","AMIZADE","AMOR",
  "AMPLO","ANDAR","ANEL","ANIMADO","ANIMAL","ANIVERSÁRIO","ANTES","ANTIGO","ANUNCIAR","APARECER",
  "APARTAMENTO","APOIO","APRENDER","APROVEITAR","AQUÁRIO","ÁRABE","ÁRVORE","ASAS","ASSAR","ASSIM",
  "ASSINAR","ASSUNTO","ATENÇÃO","ATENDER","ATENTO","ATIVO","ATIRAR","ATRÁS","AUMENTAR","AVENIDA",
  "AVIÃO","AVISO","AZEDO","AZUL",
  // B
  "BAGAGEM","BAIRRO","BAIXAR","BALÃO","BALEIA","BANCO","BANANA","BANDEIRA","BANHO","BARCO",
  "BARRO","BARULHO","BATALHA","BATATA","BATER","BEBIDA","BELEZA","BEM","BIBLIOTECA","BICICLETA",
  "BLUSA","BOCA","BOLSA","BOLO","BOMBEIRO","BONECA","BONITO","BORRACHA","BORBOLETA","BOTÃO",
  "BRANCO","BRAÇO","BRILHO","BUSCAR","BUZINA","BRAVO","BRASIL",
  // C
  "CABEÇA","CAFÉ","CAIXA","CALMA","CALOR","CAMELO","CAMINHO","CAMPO","CANÇÃO","CANSADO",
  "CANTAR","CAPITÃO","CAPAZ","CAPITAR","CARNE","CARRO","CARTA","CASA","CASTELO","CAVALO",
  "CÉREBRO","CENTRO","CERTEZA","CHAPÉU","CHAVE","CHOCOLATE","CHUVA","CIDADE","CINEMA","CIRCO",
  "CLAREZA","COBRA","COELHO","COGUMELO","COLHER","COMBATE","COMEÇO","COMIDA","COMPUTADOR","CONTAR",
  "CORAGEM","CORAÇÃO","CORRIDA","CRIAR","CRIANÇA","CUSTAR",
  // D
  "DADO","DANÇA","DANÇAR","DENTE","DENTRO","DEPRESSA","DESAFIO","DESCANSO","DESTINO","DINHEIRO",
  "DIPLOMA","DISCURSO","DISTÂNCIA","DIVERSÃO","DORMIR","DRAGÃO","DÚVIDA",
  // E
  "ESCOLA","ESCRITÓRIO","ESPAÇO","ESPELHO","ESTRADA","ESTRELA","EXEMPLO",
  // F
  "FÁBRICA","FAMÍLIA","FALAR","FAZENDA","FELIZ","FESTA","FÍGADO","FILHO","FLOR","FLORESTA",
  "FOGO","FORÇA","FORMIGA","FOTOGRAFIA","FRANGO","FRUTA","FUTEBOL","FUTURO",
  // G
  "GALINHA","GARAGEM","GATO","GELADO","GENTE","GIRASSOL","GLOBO","GOVERNO","GRANDE","GRITAR","GUARDAR","GUERRA","GUITARRA",
  // H
  "HELICÓPTERO","HISTÓRIA","HOMEM","HORA","HORIZONTE","HOSPITAL",
  // I
  "IDEIA","ILHA","IMAGEM","IMAGINAR","IMPOSTO","INÍCIO","INSETO","INTEIRO","INTELIGÊNCIA",
  // J
  "JANELA","JARDIM","JOGADOR","JOGAR","JORNAL","JOVEM",
  // L
  "LAGARTO","LAGO","LARANJA","LARGO","LEBRE","LEITE","LEOPARDO","LETRA","LÍNGUA","LIVRO",
  "LOBO","LOJA","LONGE","LUA","LUGAR","LUTAR","LUVA",
  // M
  "MAÇÃ","MADEIRA","MADRUGADA","MAMÃO","MANGA","MAPA","MÁQUINA","MAR","MÉDICO","MELHOR",
  "MENINO","MESA","METAL","MILHO","MISTÉRIO","MONTANHA","MOTOR","MUNDO","MÚSICO","MÚSICA",
  // N
  "NAÇÃO","NASCER","NATAL","NATUREZA","NAVE","NOITE","NOME","NÚMERO","NUNCA",
  // O
  "OBJETO","ÓCULOS","OLHAR","ONÇA","ÔNIBUS","OURO",
  // P
  "PAGAR","PALAVRA","PANO","PAPEL","PAREDE","PARQUE","PASSAGEM","PATO","PEDRA","PEIXE",
  "PERFUME","PESSOA","PLANETA","PLANTA","POLVO","PONTE","PORTA","PODER","PROFESSOR","PRAIA","PRESSA","PRODUTO",
  // Q
  "QUANDO","QUARTO","QUEIJO","QUÍMICA","QUINTO",
  // R
  "RÁDIO","RAPAZ","RAPOSA","RAZÃO","RELÓGIO","REINO","REMÉDIO","RESPOSTA","RIQUEZA","RISCO",
  "ROBÔ","ROCHA","RODA","ROMANCE","ROSA","ROSTO",
  // S
  "SABÃO","SAÍDA","SALA","SAÚDE","SEGREDO","SEMANA","SEMENTE","SINAL","SISTEMA","SOL","SONHO","SORTE","SUCO",
  // T
  "TÁBUA","TAMBOR","TARDE","TEATRO","TEMPO","TERRA","TIGRE","TOMATE","TRABALHO","TREM","TRIBO","TROFÉU","TUCANO",
  // U
  "UNIVERSO","URSO","UVAS",
  // V
  "VACA","VALOR","VENTO","VERDADE","VIAJAR","VIAGEM","VIDA","VIZINHO","VOCÊ","VOZ",
  // X
  "XADREZ","XÍCARA",
  // Z
  "ZEBRA","ZONA",

  // ===== EXPANSÃO MASSIVA =====
  // Verbos comuns conjugados e infinitivos
  "ABRIR","ACABAR","ACEITAR","ACHAR","AJUDAR","AMAR","ANDAR","APRENDER","CANTAR","CHAMAR",
  "CHEGAR","COMER","COMPRAR","CONHECER","CONTAR","CORRER","DANÇAR","DAR","DESCANSAR","DIZER",
  "ENTRAR","ESCREVER","ESTAR","FAZER","FALAR","FECHAR","GANHAR","GOSTAR","GRITAR","GUARDAR",
  "JOGAR","JUNTAR","LEVAR","LER","LEMBRAR","LEVANTAR","MORAR","MOSTRAR","NADAR","NASCER",
  "OLHAR","OUVIR","PAGAR","PARAR","PEDIR","PENSAR","PERDER","PODER","PULAR","QUERER",
  "SABER","SENTAR","SER","SUBIR","TOMAR","TRABALHAR","USAR","VER","VIVER","VOLTAR",

  // Substantivos do cotidiano
  "ABACATE","ABRIDOR","ACADEMIA","ACIDENTE","AÇÃO","AÇOUGUE","ADEPTO","ADMINISTRAÇÃO","ADORNO","ADOÇÃO",
  "AEROPORTO","AFETO","AGÊNCIA","AGENDA","AGONIA","AJUDA","ALEGRIA","ALFINETE","ALGODÃO","ALICATE",
  "ALMOFARIZ","ALUGUEL","AMEIXA","AMÊNDOA","AMORA","AMPOLA","ANALGÉSICO","ANDAIME","ÂNIMO","ANOTA",
  "ANSIEDADE","APARELHO","APERTO","APITO","APOSTILA","ARQUIVO","ARRANHA","ARREPIO","ARTIGO","ARVORE",
  "ASPIRO","ASSALTO","ASSINATURA","ATALHO","ATENÇÃO","ATLETISMO","ATOLEIRO","ATRAÇÃO","ATUM","AVELA",
  "AVENTAL","AVISO","AZULEJO",
  "BACIA","BAGAÇO","BAGUNÇA","BAIRRO","BAIXELA","BALDINHO","BALCÃO","BARATA","BASTIDOR","BATUQUE",
  "BENGALA","BERÇO","BEXIGA","BISCOITO","BOCADO","BOIADA","BORDO","BRILHANTE","BRINDE","BRONCA",
  "BRUXA","BURACO","BUTIQUE",
  "CAATINGA","CABANA","CAÇAMBA","CADEIRA","CAFEÍNA","CAIXOTE","CALÇADO","CALENDÁRIO","CALDO","CALÚNIA",
  "CÂMARA","CAMISA","CANETA","CANGURU","CAPOTE","CÁPSULA","CARÁTER","CARIMBO","CARNAVAL","CARRINHO",
  "CARTEIRA","CARVÃO","CASACO","CASAMENTO","CASARÃO","CAUTELA","CAVIDADE","CELULAR","CEMITÉRIO","CEREAL",
  "CERRADO","CHÁCARA","CHALEIRA","CHAMADO","CHANTAGEM","CHARUTO","CHIMARRÃO","CIDADÃO","CIMENTO","CINTO",
  "CINZA","COCO","CÓDIGO","COLEGA","COLÉGIO","COLUNA","CÔMODO","CONCURSO","CONFLITO","CONSERTO",
  "CONTRATO","CONVERSA","COPA","CORREDOR","COSTUME","COTONETE","COURO","COVARDE","COZINHA","CRISE",
  "CRUZEIRO","CUIDADO","CUNHADO","CUPOM","CURIOSO","CURRÍCULO","CURVA",
  "DAMA","DAMASCO","DÉBITO","DECRETO","DELÍCIA","DERROTA","DESAFIO","DESCONTO","DESEJO","DESGASTE",
  "DESPORTO","DETALHE","DEVAGAR","DIÁLOGO","DIETA","DIFÍCIL","DÍGITO","DILEMA","DIMINUIR","DIREITO",
  "DISCO","DISPARO","DISTÂNCIA","DIVERSIDADE","DÍVIDA","DOAÇÃO","DOENÇA","DORES","DUCHE","DUELISTA",
  "EDUCAÇÃO","ELEFANTE","ELEVADOR","EMBALAGEM","EMPREGO","EMPRESA","ENCANADOR","ENERGIA","EQUIPE","ERRO",
  "ESCADA","ESCOVA","ESCOLHA","ESGOTO","ESPORTE","ESTACA","ESTANTE","ESTIMULO","EXAME","EXCLUSIVO",
  "FACHADA","FAIXA","FALAR","FARDO","FARINHA","FATURA","FAVOR","FEIJÃO","FERIDA","FERRAMENTA",
  "FEUDO","FIAPO","FÍGADO","FILHOTE","FITA","FILETE","FOGÃO","FOFOCA","FOLHA","FORMATURA",
  "FORTALEZA","FÓSFORO","FRALDINHA","FRONTEIRA","FURTO","FUNDO",
  "GARRAFA","GAVETA","GELADEIRA","GELEIA","GENRO","GERENTE","GIRAFA","GOLEIRO","GOLPE","GONZO",
  "GRAÇA","GRIFE","GRIPE","GROSSO","GRUPO","GUARDA","GUARDA-CHUVA","GUIA","GUITARRA",
  "HÁBITO","HAMBÚRGUER","HAMSTER","HERANÇA","HERÓI","HIENA","HIGIENE","HIPÓCRITA","HORÁRIO","HORTA",
  "HUMANO","HUMOR",
  "IATE","IDIOMA","IGUAL","IMPOSTO","IMPULSO","INCÊNDIO","INFÂNCIA","INFLAÇÃO","INGÊNUO","INIMIGO",
  "INQUILINO","INSTINTO","INTENÇÃO","INVEJA","IOGURTE",
  "JANTAR","JAQUETA","JARRO","JEITO","JILÓ","JOELHO","JUNTO",
  "LARVA","LASTRO","LÁTEX","LATIDO","LAVAGEM","LAVANDERIA","LEALDADE","LEGUME","LEVEZA","LIMÃO",
  "LIMPEZA","LINDEZA","LÍNGUA","LITORAL","LIVRARIA","LOGOTIPO","LOTAÇÃO","LANCHE",
  "MACACO","MACONHA","MADURO","MADRASTA","MAGNÓLIA","MALANDRO","MALETA","MANCHETE","MANTEIGA","MAPA",
  "MAÇANETA","MARISCO","MÁRMORE","MASTRO","MATERIAL","MÁXIMO","MAZELA","MECANISMO","MENDIGO","MENTIRA",
  "MERCADO","METRÔ","MILAGRE","MILITAR","MÍNIMO","MOCHILA","MODELO","MOLHO","MORADA","MOTIVO",
  "MOÇO","MUAMBA","MUNIÇÃO","MUSEU",
  "NAVALHA","NECESSIDADE","NEGOCIO","NEVADA","NÍTIDO","NÍVEL","NOÇÃO","NOSTALGIA","NOTA","NOVELA",
  "NUVEM",
  "OCIOSO","OFERTA","OFICIAL","OPERAÇÃO","OPRESSÃO","ORAÇÃO","ORCA","ORGANISMO","ORGULHO","ORIGEM",
  "ORQUESTRA",
  "PACIENTE","PACOTE","PADRÃO","PADRASTO","PAINEL","PALÁCIO","PALHAÇO","PALMEIRA","PANELA","PANORAMA",
  "PARCEIRO","PÁSSARO","PASTAGEM","PÁTIO","PAVILHÃO","PECADO","PENHASCO","PEPINO","PERCURSO","PERIGO",
  "PESQUISA","PETRÓLEO","PIMENTA","PISCINA","PISTOLA","PITOMBA","PIZZARIA","PLATAFORMA","PLATEIA","PLAYBOY",
  "POEMA","POLENTA","POLÍTICO","POLUIÇÃO","POMADA","PORÇÃO","PORTEIRO","POUSADA","PRAZO","PRESENTE",
  "PRESÍDIO","PRINCESA","PRINCÍPIO","PRIVADO","PROCESSO","PROIBIÇÃO","PROJETO","PROMESSA","PROPRIETÁRIO","PROTEÇÃO",
  "PÚBLICO","PUREZA",
  "QUALIDADE","QUERIDA","QUÍMICA","QUOTIDIANO",
  "RAINHA","REAÇÃO","RECADO","RECEITA","RECIBO","RECURSO","REDE","REFORMA","REGRA","RELAÇÃO",
  "RELIGIÃO","REPROVA","RESERVA","RESIDÊNCIA","RESOLUÇÃO","RESULTADO","REUNIÃO","REVOLTA","RIQUEZA","RITUAL",
  "ROTINA","ROUBO","RUIDOSO",
  "SACRIFÍCIO","SAGRADO","SANDUÍCHE","SANGUE","SAUDADE","SECO","SENTIDO","SERVIÇO","SILÊNCIO","SIMPÁTICO",
  "SINUCA","SITUAÇÃO","SOFRIMENTO","SOLUÇÃO","SOMBRA","SUFOCO","SUÍÇO","SUJEITO","SUPOSTO","SURPRESA",
  "SUSPIRO","SUTURA",
  "TABELA","TÁXI","TÉCNICA","TELEFONE","TELEVISÃO","TENDÊNCIA","TENSÃO","TEORIA","TESTEMUNHA","TIROTEIO",
  "TOMADA","TORRADA","TORTINHA","TOURADA","TRADIÇÃO","TRANSPORTE","TRIÂNGULO","TRIBUNAL","TRISTEZA","TRONCO",
  "TUBERCULOSE","TUMBA",
  "URGENTE","ÚTERO","UTOPIA","UXÓRIO",
  "VAIDADE","VACINA","VALIDAR","VAPORIZADOR","VARANDA","VARGEM","VAZAMENTO","VEGETAL","VELOCIDADE","VENENO",
  "VERGONHA","VERMELHO","VESTUÁRIO","VITÓRIA","VIZINHANÇA","VOCABULÁRIO","VODKA","VOLUME",
  "XILOGRAVURA","XINGAMENTO",
  "ZANGADO","ZIPPER","ZUMBIDO",

  // Adjetivos e outros
  "ÁGIL","ALTO","AMÁVEL","ANTIGO","BAIXO","BONITO","CAPAZ","CERTO","CLARO","CONFUSO",
  "CURIOSO","DIFÍCIL","ENGRAÇADO","ESPECIAL","ESTRANHO","EXATO","FAMOSO","FANTÁSTICO","FELIZ","FINO",
  "FIRME","FORTE","FRACO","FRESCO","GENTIL","GORDO","GRAVE","HONESTO","IMPORTANTE","INCRÍVEL",
  "JUSTO","LARGO","LEVE","LINDO","LIVRE","LOUCO","MAGRO","MÁGICO","MALSÃO","MANSO",
  "MEIGO","MISTERIOSO","MODERNO","NECESSÁRIO","NOBRE","NOVO","OBJETIVO","ÓTIMO","PÁLIDO","PEQUENO",
  "PERFEITO","PESADO","POSITIVO","PRECIOSO","PRONTO","PRUDENTE","QUIETO","RICO","SAGRADO","SAUDÁVEL",
  "SECO","SEGURO","SIMPLES","SINCERO","SOLITÁRIO","SUAVE","SUJO","TÍMIDO","TRANQUILO","ÚTIL",
  "VALENTE","VERDADEIRO","VELHO","VIGOROSO","VIOLENTO",

  // Palavras com acento (também serão normalizadas no servidor)
  "AÇÃO","ESTAÇÃO","SOLUÇÃO","NAÇÃO","EDUCAÇÃO","RELAÇÃO","SITUAÇÃO","CONDIÇÃO","OPERAÇÃO","PRODUÇÃO",
  "TRADIÇÃO","FUNÇÃO","POSIÇÃO","REAÇÃO","ATENÇÃO","MISSÃO","VISÃO","PAIXÃO","PROTEÇÃO","GESTÃO",
]);

// Palavras válidas para sortear como segredos (tamanho 4–12, sem caracteres especiais problemáticos)
const PALAVRAS_SECRETAS = [...DICIONARIO].filter(w => w.length >= 4 && w.length <= 10);

/**
 * Normaliza uma string removendo acentos e convertendo para maiúsculas
 */
function normalizar(str) {
  return str.trim().toUpperCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/**
 * Verifica se uma palavra existe no dicionário (com normalização de acentos)
 */
function existeNoDicionario(palavra) {
  const norm = normalizar(palavra);
  // Verifica tanto a forma normalizada quanto a original maiúscula
  if (DICIONARIO.has(norm)) return true;
  // Verifica cada entrada do dicionário após normalização
  for (const entrada of DICIONARIO) {
    if (normalizar(entrada) === norm) return true;
  }
  return false;
}

module.exports = { DICIONARIO, PALAVRAS_SECRETAS, normalizar, existeNoDicionario };